### ISSUE TITLE
HaystackContinued.cs:161 method 'OnDestory' is probably never getting called

### ISSUE THREAD

**Issue by Hotel26** [linuxgurugamer/HaystackContinued#12]
TranspoTypo in the name 'OnDestory' probably means that the underlying 'OnDestroy' method in MonoBehaviour is getting called instead?

**Comment by rsparkyc** [comment]
looks like this was indeed an issue, and was fixed here: https://github.com/linuxgurugamer/HaystackContinued/commit/92aff95fac29a7c9b90c644c7d17fb2076cf3548
