### ISSUE TITLE
Latest download contains wrong mod

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/HaystackContinued#7]
The latest download on SpaceDock:

https://spacedock.info/mod/1680/Haystack%20ReContinued/download/0.1.9.13

... contains HullCameraVDS instead of this mod:

![image](https://user-images.githubusercontent.com/1559108/50983320-2878e500-14f7-11e9-9b26-477db05b6804.png)

**Comment by linuxgurugamer** [comment]
nuts.
Thanks for letting me know, I'll update it

**Comment by linuxgurugamer** [comment]
I deleted the bad one and uploaded the correct one, can you make sure the ckan meta data is good?
thanks

**Comment by HebaruSan** [comment]
Confirmed fixed, thanks.
